site_name: ecsctl
site_description: A CLI tool for managing Amazon ECS resources, inspired by eksctl.
site_author: Roslaan001
site_url: https://Roslaan001.github.io/ecsctl

theme:
  name: material
  palette:
    # Palette toggle for dark / light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Getting Started: index.md
  - Installation: installation.md
  - Declarative Management: declarative.md
  - Operations & Commands: commands.md
  - Resource Inspection: inspection.md
  - Remote State: state.md
  - CLI Reference: reference.md
